/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal installs. It is committed here
// because the project was scaffolded manually in an environment without npm.
